blog/urls.py
from django.urls import path
from .views import IndexView, detail, category

app_name = 'blog'
urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('<int:pk>/', detail, name='detail'),
    path('<category_name>/', category, name='category'),
]

personal_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('portfolio.urls')),
    path('blog/', include('blog.urls')),
]

portfolio/urls.py
from django.urls import path
from .views import IndexView, DetailView

app_name = 'portfolio'
urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('<int:pk>/', DetailView.as_view(), name='detail')
]

blog/models.py
from django.db import models


class Category(models.Model):

    def __str__(self):
        return self.name

    name = models.CharField(max_length=20)


class Post(models.Model):

    def __str__(self):
        return self.title

    title = models.CharField(max_length=255)
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    last_modified = models.DateTimeField(auto_now=True)
    categories = models.ManyToManyField(Category, related_name='posts')


class Comment(models.Model):

    def __str__(self):
        return self.author

    author = models.CharField(max_length=60)
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

portfolio/models.py
from django.db import models


class Project(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    technology = models.CharField(max_length=20)
    image = models.FilePathField(path="/portfolio/img")

blog/forms.py
from django import forms


class CommentForm(forms.Form):
    author = forms.CharField(
        max_length=60,
        widget=forms.TextInput(attrs={
            "class": "form-control",
            "placeholder": "Your Name"
        })
    )
    body = forms.CharField(widget=forms.Textarea(
        attrs={
            "class": "form-control",
            "placeholder": "Leave a comment!"
        })
    )
    email = forms.EmailField(widget=forms.EmailInput())

blog/views.py
from django.shortcuts import render
from django.views import generic

from .models import Post, Comment
from .forms import CommentForm


class IndexView(generic.ListView):
    model = Post
    context_object_name = 'posts'
    template_name = 'blog/index.html'

    def get_queryset(self):
        return Post.objects.all().order_by('-created_on')


def detail(request, pk):
    post = Post.objects.get(pk=pk)

    form = CommentForm()
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = Comment(
                author=form.cleaned_data["author"],
                body=form.cleaned_data["body"],
                post=post
            )
            comment.save()

    comments = Comment.objects.filter(post=post)
    context = {
        "post": post,
        "comments": comments,
        "form": form,
    }
    return render(request, "blog/detail.html", context)


def category(request, category_name):
    posts = Post.objects.filter(
        categories__name__contains=category_name
    ).order_by(
        '-created_on'
    )
    context = {
        "category": category_name,
        "posts": posts
    }
    return render(request, "blog/category.html", context)

portfolio/views.py
from django.views import generic

from .models import Project


class IndexView(generic.ListView):
    model = Project
    template_name = 'portfolio/index.html'
    context_object_name = 'projects'


class DetailView(generic.DetailView):
    model = Project
    template_name = 'portfolio/detail.html'

blog/templates/blog/category.html
{% extends "base.html" %}
{% block blog_active %}Active{% endblock %}
{% block content %}
<div class="col-md-8 offset-md-2">
    <h1>{{ category | title }}</h1>
    <hr>
    {% for post in posts %}
        <h2><a href="{% url 'blog:detail' post.pk%}">{{ post.title }}</a></h2>
        <small>
            {{ post.created_on.date }} |&nbsp;
            Categories:&nbsp;
            {% for category in post.categories.all %}
            <a href="{% url 'blog:category' category.name %}">
                {{ category.name }}
            </a>&nbsp;
            {% endfor %}
        </small>
        <p>{{ post.body | slice:":400" }}...</p>
    {% endfor %}
</div>
{% endblock %}

blog/templates/blog/detail.html
{% extends "base.html" %}
{% block blog_active %}Active{% endblock %}
{% block content %}
<div class="col-md-8 offset-md-2">
    <h1>{{ post.title }}</h1>
    <small>
        {{ post.created_on.date }} |&nbsp;
        Categories:&nbsp;
        {% for category in post.categories.all %}
        <a href="{% url 'blog:category' category.name %}">
            {{ category.name }}
        </a>&nbsp;
        {% endfor %}
    </small>
    <p>{{ post.body | linebreaks }}</p>
    <h3>Leave a comment:</h3>
    <form action="/blog/{{ post.pk }}/" method="post">
        {% csrf_token %}
        <div class="form-group">
            {{ form.author }}
        </div>
        <div class="form-group">
            {{ form.body }}
        </div>
        <div class="form-group">
            {{ form.email }}
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
    <h3>Comments:</h3>
    {% for comment in comments %}
    <p>
        On {{comment.created_on.date }}&nbsp;
        <b>{{ comment.author }}</b> wrote:
    </p>
    <p>{{ comment.body }}</p>
    <hr>
    {% endfor %}
</div>
{% endblock %}

blog/templates/blog/index.html
{% extends "base.html" %}
{% block blog_active %}Active{% endblock %}
{% block content %}
{% if posts %}
    <div class="col-md-8 offset-md-2">
        <h1>Blog Index</h1>
        <hr>
        {% for post in posts %}
        <h2><a href="{% url 'blog:detail' post.pk%}">{{ post.title }}</a></h2>
        <small>
            {{ post.created_on.date }} |&nbsp;
            Categories:&nbsp;
            {% for category in post.categories.all %}
            <a href="{% url 'blog:category' category.name %}">
                {{ category.name }}
            </a>&nbsp;
            {% endfor %}
        </small>
        <p>{{ post.body | slice:":400" }}...</p>
        {% endfor %}
    </div>
{% else %}
    <h2>No posts are available</h2>
{% endif %}
{% endblock %}

portfolio/templates/portfolio/detail.html
{% extends "base.html" %}
{% block home_active %}Active{% endblock %}
{% load static %}

{% block content %}
<h1>{{ project.title }}</h1>
<div class="row">
    <div class="col-md-8">
        <img src="{% static project.image %}" alt="" width="100%">
    </div>
    <div class="col-md-4">
        <h5>About the project:</h5>
        <p>{{ project.description }}</p>
        <br>
        <h5>Technology used:</h5>
        <p>{{ project.technology }}</p>
    </div>
</div>
{% endblock %}

portfolio/templates/portfolio/index.html
{% extends "base.html" %}
{% block home_active %}Active{% endblock %}
{% load static %}

{% block content %}
    <h1>Projects</h1>
    {% if projects %}
        <div class="row">
            {% for project in projects %}
            <div class="col-md-4">
                <img class="card-img-top" src="{% static project.image %}">
                <div class="card-body">
                    <h5 class="card-title">{{ project.title }}</h5>
                    <p class="card-text">{{ project.description }}</p>
                    <a href="{% url 'portfolio:detail' project.pk %}"
                       class="btn btn-primary">
                        Read More
                    </a>
                </div>
            </div>
            {% endfor %}
        </div>
    {% else %}
        <p> No Projects are available. </p>
    {% endif %}
{% endblock %}

templates/base.html
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <a class="navbar-brand" href="{% url 'portfolio:index' %}">Portfolio</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item {% block home_active %}{% endblock %}">
              <a class="nav-link" href="{% url 'portfolio:index' %}">Home</a>
            </li>
            <li class="nav-item {% block blog_active %}{% endblock %}">
              <a class="nav-link" href="{% url 'blog:index' %}">Blog</a>
            </li>
          </ul>
        </div>
    </div>

</nav>

<div class="container">
    {% block content %}{% endblock %}
</div>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>